# This workflow checks for common grammar and spelling mistakes in markdown docs files.
name: Spellcheck

on:
  pull_request:
    branches: [main, develop]

jobs:
  spellcheck:
    name: Check Grammar and Spelling errors
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v5

      - name: Setup Bun ⚙️
        uses: oven-sh/setup-bun@v2

      - name: Install ⚙️
        run: bun install --frozen-lockfile

      - name: Check spelling errors in docs 🔍
        uses: codespell-project/actions-codespell@v2
        with:
          check_filenames: true
          check_hidden: true
          skip: ./.git/**/*,bun.lock,./node_modules/**/*,./node_modules/.*,./.astro/**/*,./dist/**/*,./public/**/*,./.sdk-cache/**/*,./src/content/docs/typescript-sdk/api-reference/**/*
          ignore_words_list: arkiv,astro,starlight,typedoc,braga,kaolin,atleast
